### ISSUE TITLE
Conditional access operator with non-proc 

### ISSUE THREAD

**Issue by geekrelief** [mattaylor/elvis#1]
I'm doing interop with C, and I have lots of structures that have pointer values. I want to use a conditional access operator in combination with a truthy operator like this:

```nim
  if ?data?.shader:
    # use the data.shader
```

But the current implementation expects shader to be a proc.  Should I create a new operator for my use case or do you think `?.` could be modified to handle this?

**Comment by geekrelief** [comment]
Looks like I'll have to rewrite `?.` into a macro if I want to preserve the current behavior and handle my use case.

**Comment by mattaylor** [comment]
do any of the following work for your use case?
` if ?data.shader: `  // should be false as an exception will be thrown
`  if ?(data?.shader): ` // should be false if data is false or data.shader is false
`  if ?data && ?data.shader:` // // should be false if data is false or data.shader is false

**Comment by geekrelief** [comment]
I'm currently using `if ?data and ?data.shader`, with the change of `?.` to `.?` I can now do `if ?data.?shader:`

But I also modified the template to look like:
```nim
template `.?`*(left, right: untyped): untyped =
  if ?left: 
    left.right
  else: 
    var res: typeof(left.right)
    res
```

**Comment by mattaylor** [comment]
Can this be closed now?
