### ISSUE TITLE
Change conditional access operator `?.` for higher precedence?

### ISSUE THREAD

**Issue by geekrelief** [mattaylor/elvis#3]
`?.` has lower precedence than `==` https://nim-lang.github.io/Nim/manual.html#syntax-precedence

If we wanted to do something like:
```nim
if d?.val == 10:
  echo "foo"
```
We would need to wrap the expression in parentheses:
```nim
if (d?.val) == 10:
  echo "foo"
```

If we change the operator to `.?` then this works:

```nim
if d.?val == 10:
  echo "foo"
```

**Comment by mattaylor** [comment]
good catch. Any suggestions how to  fix this?

**Comment by geekrelief** [comment]
I suggest renaming the operator to `.?` since dot operators have higher precedence than operators with `=`.
