### ISSUE TITLE
Chaining `.?`

### ISSUE THREAD

**Issue by geekrelief** [mattaylor/elvis#4]
Thanks for the changes! I was going to push a PR, but you saved me the trouble. :)

I'm currently, trying to figure out how to chain `.?` so we can do: 
```nim
var val = obj.?data.?val
```

I'm looking at https://nim-lang.github.io/Nim/manual_experimental.html#special-operators-dot-operators or https://nim-lang.github.io/Nim/manual_experimental.html#pattern-operators-the-nimstar-operator but I haven't figured it out yet.

**Comment by mattaylor** [comment]
fixed
